import { language } from "./language";

/*---------------------------------------------------------
 * Copyright (C) Adam Najmanowicz. All rights reserved.
 *--------------------------------------------------------*/

export const sitecoreFunctions = [
    {
        "name": "sc_field",
        "description": "Renders Sitecore Field",
        "validationRegEx": "",
        "template": "sc_field ${1|item,datasource,page,site|} '${2:FieldName}'",
        "codeBlock" : "{{ sc_field item 'FieldName' }}",
        "pipeTemplate": "sc_field '${2:FieldName}'",
        "pipeCodeBlock" : "{{ ... | sc_field 'FieldName' }}",
    },
    {
        "name": "sc_field",
        "description": "Renders Sitecore Field falling back to next field on the list if the previous one is empty",
        "validationRegEx": "",
        "template": "sc_field ${1|item,datasource,page,site|} ['${2:FieldName1}','${3:FieldName2}']",
        "codeBlock" : "{{ sc_field item ['FieldName1','FieldName2'] }}",
        "pipeTemplate": "sc_field ['${2:FieldName1}','${3:FieldName2}']",
        "pipeCodeBlock" : "{{ ... | sc_field item ['FieldName1','FieldName2'] }}",
    },
    {
        "name": "sc_field",
        "description": "Renders Sitecore Field with added parameters to tags for e.g. image or link",
        "validationRegEx": "",
        "template": "sc_field ${1|item,datasource,page,site|} '${2:FieldName}' [['${3:data-attribute1}','${4:value1}'],['${5:data-attribute2}','${6:value2}']]",
        "codeBlock" : "{{ sc_field item 'FieldName' [['data-attribute1','value1'],['data-attribute2','value2']] }}",
        "pipeTemplate": "sc_field '${2:FieldName}' [['${3:data-attribute1}','${4:value1}'],['${5:data-attribute2}','${6:value2}']]",
        "pipeCodeBlock" : "{{ ... | sc_field 'FieldName' [['data-attribute1','value1'],['data-attribute2','value2']]'] }}",
    },
    {
        "name": "sc_decorate",
        "description": "Outputs component decoration with styles, grid classes and attributes needed by creative exchange",
        "validationRegEx": "",
        "template": "sc_decorate",
        "codeBlock" : "{{ sc_decorate }}",
        "pipeTemplate": "",
        "pipeCodeBlock" : "",
    },
    {
        "name": "sc_decorate",
        "description": "Outputs component decoration with styles, grid classes and attributes needed by creative exchange",
        "validationRegEx": "",
        "template": "sc_decorate ['${1:css-class}']",
        "codeBlock" : "{{ sc_decorate ['css-class'] }}",
        "pipeTemplate": "",
        "pipeCodeBlock" : "",
    },
    {
        "name": "sc_translate",
        "description": "Translate a label to the context language or the language specified as a parameter using the site dictionary.",
        "validationRegEx": "",
        "template": "sc_translate \"${1:phrase}\" ${2:\"languagename\"",
        "codeBlock" : "sc_translate \"phrase\" \"languagename\"}",
        "pipeTemplate": "sc_translate ${1:\"languagename\"}",
        "pipeCodeBlock" : "sc_translate \"languagename\"",
    },
    {
        "name": "sc_editframe",
        "description": "Wrapping block for an edit frame",
        "validationRegEx": "",
        "template": ["{{ sc_editframe ${1|item,datasource,page,site|} '${2:FrameName}' }}",
        "$3",
        "{{ sc_endeditframe }}"],
        "codeBlock" : "{{ sc_editframe item 'FrameName' }}\n\n{{ sc_endeditframe }}",
        "pipeTemplate": "",
        "pipeCodeBlock" : "",
    },
    {
        "name": "sc_execute",
        "description": "Renders variant beneath the current script providing item to the pipeline",
        "validationRegEx": "",
        "template": "sc_execute ${1|item,datasource,page,site|} '${2:SubVariantName}'",
        "codeBlock" : "{{ sc_execute item 'SubVariantName' }}",
        "pipeTemplate": "sc_execute '${2:SubVariantName}'",
        "pipeCodeBlock" : "{{ sc_execute 'SubVariantName' }}",
    },
    {
        "name": "sc_evaluate",
        "description": "Evaluates a rule stored in an item beneath the scriban script - allows specifying item for evaluation. Returns boolean value",
        "validationRegEx": "",
        "template": "sc_evaluate ${1|item,datasource,page,site|} '${2:Rule Name}'",
        "codeBlock" : "{{ sc_evaluate item 'Rule Name' }}",
        "pipeTemplate": "sc_evaluate '${2:Rule Name}'",
        "pipeCodeBlock" : "sc_evaluate 'Rule Name'",
    },
    {
        "name": "",
        "description": "",
        "validationRegEx": "",
        "template": "",
        "codeBlock" : "",
        "pipeTemplate": "",
        "pipeCodeBlock" : "",
    },
];
